magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "0" out0.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "1" out1.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "2" out2.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "3" out3.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "4" out4.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "5" out5.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "6" out6.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "7" out7.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "8" out8.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "9" out9.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "10" out10.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "11" out11.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "12" out12.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "13" out13.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "14" out14.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "15" out15.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "16" out16.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "17" out17.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "18" out18.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "19" out19.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "20" out20.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "21" out21.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "22" out22.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "23" out23.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "24" out24.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "25" out25.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "26" out26.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "27" out27.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "28" out28.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "29" out29.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "30" out30.bmp
magick eye.bmp -pointsize 20 -gravity South -font trebuchet-ms -fill white -annotate +0+0 "31" out31.bmp